<?php

namespace AppBundle\Repository;

/**
 * EtalageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtalageRepository extends \Doctrine\ORM\EntityRepository
{
}
